### ISSUE TITLE
Fatal error: Couldn't find any fabfiles! Remember that -f can be used to specify fabfile path, and use -h for help.

### ISSUE THREAD

**Issue by lili2018** [AKSHAYUBHAT/DeepVideoAnalytics#107]
I removed all containers and did these instructions:
1)git clone https://github.com/AKSHAYUBHAT/DeepVideoAnalytics
2)cd DeepVideoAnalytics/docs/tutorial && docker-compose up
---------------------------------------------------------------------------------
again, I have problem: dva-server exited with code 1
---------------------------------------------------------------------------------
docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                     PORTS                                NAMES
be04b4eba8d0        akshayubhat/dva-auto:latest   "bash -c 'youtube-..."   20 minutes ago      Exited (1) 7 minutes ago                                        dva-server
48ea9976e206        3783875a2039                  "/bin/sh -c 'pip i..."   3 hours ago         Exited (2) 3 hours ago                                          compassionate_swartz
d5fcde4d4e1d        3783875a2039                  "/bin/sh -c 'pip i..."   3 hours ago         Exited (2) 3 hours ago                                          sharp_joliot
c2f2e5425191        3783875a2039                  "/bin/sh -c 'pip i..."   3 hours ago         Exited (2) 3 hours ago                                          quizzical_carson
7b351b4c07a5        3783875a2039                  "/bin/sh -c 'pip i..."   3 hours ago         Exited (2) 3 hours ago                                          eager_boyd
4829033f086e        16a65b760382                  "/bin/sh -c 'git c..."   4 hours ago         Exited (128) 4 hours ago                                        frosty_agnesi
b78bbe061a92        16a65b760382                  "/bin/sh -c 'git c..."   4 hours ago         Exited (128) 4 hours ago                                        wizardly_albattani
5ebad05e8da0        16a65b760382                  "/bin/sh -c 'git c..."   4 hours ago         Exited (128) 4 hours ago                                        elegant_yonath
4f8900c7bdd2        16a65b760382                  "/bin/sh -c 'git c..."   4 hours ago         Exited (128) 4 hours ago                                        blissful_hugle
ca664c2b5be4        rabbitmq                      "docker-entrypoint..."   5 hours ago         Up 8 minutes               4369/tcp, 5671-5672/tcp, 25672/tcp   dva-rmq
c44a083b21da        postgres:9.6.6                "docker-entrypoint..."   5 hours ago         Up 8 minutes               5432/tcp                             dva-pg
fe8b7a8b5a92        abfc48b5a41a                  "/bin/sh -c 'pip i..."   5 hours ago         Exited (1) 5 hours ago                                          unruffled_lewin
79a84a580f67        abfc48b5a41a                  "/bin/sh -c 'pip i..."   5 hours ago         Exited (1) 5 hours ago                                          keen_meitner
e70e4f934f0f        2e7c760307df                  "/bin/sh -c 'apt-g..."   6 hours ago         Exited (100) 6 hours ago                                        agitated_hamilton
---------------------------------------------------------------------------------------------------------------------------
docker logs dva-server
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
youtube-dl is up-to-date (2017.12.23)
From https://github.com/akshayubhat/DeepVideoAnalytics
   3cde4c1..b17a894  master     -> origin/master
Updating 3cde4c1..b17a894
Fast-forward
 .travis.yml                                     |   4 +-
 configs/readme.md                               |   2 +-
 deploy/cpu/docker-compose-non-nfs.yml           |  26 +--
 deploy/cpu/docker-compose.yml                   |   2 +-
 deploy/dev/docker-compose.yml                   |   2 +-
 deploy/gcp/deployments/coco.yaml                |   2 +-
 deploy/gcp/deployments/crnn.yaml                |   2 +-
 deploy/gcp/deployments/extractor.yaml           |   2 +-
 deploy/gcp/deployments/face.yaml                |   2 +-
 deploy/gcp/deployments/facenet.yaml             |   2 +-
 deploy/gcp/deployments/facenet_retriever.yaml   |   2 +-
 deploy/gcp/deployments/inception.yaml           |   2 +-
 deploy/gcp/deployments/inception_retriever.yaml |   2 +-
 deploy/gcp/deployments/scheduler.yaml           |   2 +-
 deploy/gcp/deployments/tagger.yaml              |   2 +-
 deploy/gcp/deployments/textbox.yaml             |   2 +-
 deploy/gcp/deployments/webserver.yaml           |   2 +-
 deploy/gpu/docker-compose-gpu-low-memory.yml    |   4 +-
 deploy/gpu/docker-compose-gpu.yml               |   2 +-
 docs/tutorial/docker-compose.yml                |   2 +-
 server/copy_defaults.py                         |  10 +
 server/dvaapp/task_shared.py                    |   2 +-
 server/fabfile.py                               | 253 ------------------------
 server/init_fs.py                               |  66 +++++++
 server/launch_from_env.py                       |  93 +++++++++
 server/start_container.py                       |  20 ++
 server/start_scheduler.py                       |  12 ++
 server/startq.py                                |  40 ++++
 tests/clean.py                                  |   4 +-
 tests/launch.sh                                 |   2 +-
 30 files changed, 279 insertions(+), 291 deletions(-)
 create mode 100755 server/copy_defaults.py
 delete mode 100755 server/fabfile.py
 create mode 100755 server/init_fs.py
 create mode 100755 server/launch_from_env.py
 create mode 100755 server/start_container.py
 create mode 100755 server/start_scheduler.py
 create mode 100755 server/startq.py

Fatal error: Couldn't find any fabfiles!

Remember that -f can be used to specify fabfile path, and use -h for help.

Aborting.
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
youtube-dl is up-to-date (2017.12.23)
Already up-to-date.
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
youtube-dl is up-to-date (2017.12.23)
Already up-to-date.

Fatal error: Couldn't find any fabfiles!

Remember that -f can be used to specify fabfile path, and use -h for help.

Aborting.
dva-server exited with code 1

**Comment by AKSHAYUBHAT** [comment]
I have significantly modified the code, and removed fabfiles. Please delete and reclone/download the repo/directory on the host OS.

**Comment by lili2018** [comment]
I deleted and recloned  the repo/directory on the host OS. I cannot access UI.
-------------------------------------
docker logs dva-server
From https://github.com/akshayubhat/DeepVideoAnalytics
   3cde4c1..a75e85b  master     -> origin/master
Updating 3cde4c1..a75e85b
Fast-forward
 .travis.yml                                     |   4 +-
 configs/custom_defaults/init_process.json       |   8 +-
 configs/readme.md                               |   2 +-
 deploy/cpu/docker-compose-non-nfs.yml           |  84 +++----
 deploy/cpu/docker-compose.yml                   |   2 +-
 deploy/cpu/webserver_logs.sh                    |   2 +-
 deploy/dev/docker-compose.yml                   |   2 +-
 deploy/gcp/deployments/coco.yaml                |   2 +-
 deploy/gcp/deployments/crnn.yaml                |   2 +-
 deploy/gcp/deployments/extractor.yaml           |   2 +-
 deploy/gcp/deployments/face.yaml                |   2 +-
 deploy/gcp/deployments/facenet.yaml             |   2 +-
 deploy/gcp/deployments/facenet_retriever.yaml   |   2 +-
 deploy/gcp/deployments/global_retriever.yaml    |  89 ++++++++
 deploy/gcp/deployments/inception.yaml           |   2 +-
 deploy/gcp/deployments/inception_retriever.yaml |   2 +-
 deploy/gcp/deployments/scheduler.yaml           |   2 +-
 deploy/gcp/deployments/tagger.yaml              |   2 +-
 deploy/gcp/deployments/textbox.yaml             |   2 +-
 deploy/gcp/deployments/webserver.yaml           |   2 +-
 deploy/gcp/launch.sh                            |  10 +-
 deploy/gpu/docker-compose-gpu-low-memory.yml    |   4 +-
 deploy/gpu/docker-compose-gpu.yml               |   2 +-
 docs/tutorial/docker-compose.yml                |   2 +-
 server/copy_defaults.py                         |  10 +
 server/dva/settings.py                          |  75 +++----
 server/dvaapp/operations/analysis.py            |   2 +-
 server/dvaapp/operations/detection.py           |   2 +-
 server/dvaapp/operations/indexing.py            |   2 +-
 server/dvaapp/operations/retrieval.py           |  17 +-
 server/dvaapp/processing.py                     |   4 +-
 server/dvaapp/task_shared.py                    |   2 +-
 server/dvaapp/tasks.py                          | 282 +++++++++++-------------
 server/dvaui/models.py                          |   2 +-
 server/dvaui/view_shared.py                     |   4 +-
 server/fabfile.py                               | 253 ---------------------
 server/init_fs.py                               |  70 ++++++
 server/launch_from_env.py                       |  96 ++++++++
 server/start_container.py                       |  24 ++
 server/start_scheduler.py                       |  12 +
 server/startq.py                                |  40 ++++
 tests/clean.py                                  |   4 +-
 tests/launch.sh                                 |   2 +-
 tests/test_ci_search.py                         |   2 +-
 44 files changed, 580 insertions(+), 560 deletions(-)
 create mode 100644 deploy/gcp/deployments/global_retriever.yaml
 create mode 100755 server/copy_defaults.py
 delete mode 100755 server/fabfile.py
 create mode 100755 server/init_fs.py
 create mode 100755 server/launch_from_env.py
 create mode 100755 server/start_container.py
 create mode 100755 server/start_scheduler.py
 create mode 100755 server/startq.py
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
System check identified some issues:

WARNINGS:
?: (rest_framework.W001) You have specified a default PAGE_SIZE pagination rest_framework setting,without specifying also a DEFAULT_PAGINATION_CLASS.
	HINT: The default for DEFAULT_PAGINATION_CLASS is None. In previous versions this was PageNumberPagination. If you wish to define PAGE_SIZE globally whilst defining pagination_class on a per-view basis you may silence this check.
No changes detected
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
System check identified some issues:

WARNINGS:
?: (rest_framework.W001) You have specified a default PAGE_SIZE pagination rest_framework setting,without specifying also a DEFAULT_PAGINATION_CLASS.
	HINT: The default for DEFAULT_PAGINATION_CLASS is None. In previous versions this was PageNumberPagination. If you wish to define PAGE_SIZE globally whilst defining pagination_class on a per-view basis you may silence this check.
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying django_celery_beat.0001_initial... OK
  Applying django_celery_beat.0002_auto_20161118_0346... OK
  Applying django_celery_beat.0003_auto_20161209_0049... OK
  Applying django_celery_beat.0004_auto_20170221_0000... OK
  Applying django_celery_results.0001_initial... OK
  Applying dvaapp.0001_initial... OK
  Applying dvaapp.custom_migration... OK
  Applying dvaapp.0001_auto_20170825_1749... OK
  Applying dvaapp.0002_detector_queue... OK
  Applying dvaapp.0003_auto_20170826_0041... OK
  Applying dvaapp.0004_auto_20170826_0641... OK
  Applying dvaapp.0005_auto_20170826_1539... OK
  Applying dvaapp.0006_auto_20170826_1617... OK
  Applying dvaapp.0007_auto_20170826_1644... OK
  Applying dvaapp.0008_auto_20170826_1644... OK
  Applying dvaapp.0009_auto_20170826_1918... OK
  Applying dvaapp.0010_auto_20170827_1626... OK
  Applying dvaapp.0011_auto_20170828_2143... OK
  Applying dvaapp.0012_auto_20170829_0528... OK
  Applying dvaapp.0013_indexentries_indexer_shasum... OK
  Applying dvaapp.0014_auto_20170829_0635... OK
  Applying dvaapp.0015_retriever_name... OK
  Applying dvaapp.0016_auto_20170829_0959... OK
  Applying dvaapp.0017_auto_20170829_1016... OK
  Applying dvaapp.0018_auto_20170831_2141... OK
  Applying dvaapp.0019_auto_20170831_2238... OK
  Applying dvaapp.0020_retriever_last_built... OK
  Applying dvaapp.0021_remove_video_query... OK
  Applying dvaapp.0022_auto_20170901_2329... OK
  Applying dvaapp.0023_auto_20170902_0516... OK
  Applying dvaapp.0024_systemstate... OK
  Applying dvaapp.0025_auto_20170903_0141... OK
  Applying dvaapp.0026_worker... OK
  Applying dvaapp.0027_worker_queue_name... OK
  Applying dvaapp.0028_auto_20170905_1842... OK
  Applying dvaapp.0029_queryregion... OK
  Applying dvaapp.0030_queryregionindexvector... OK
  Applying dvaapp.0031_auto_20170913_1927... OK
  Applying dvaapp.0032_queryregionresults... OK
  Applying dvaapp.0033_auto_20170920_0340... OK
  Applying dvaapp.0034_auto_20171004_0351... OK
  Applying dvaapp.0035_auto_20171004_0403... OK
  Applying dvaapp.0036_deepmodel_parent... OK
  Applying dvaapp.0037_auto_20171022_0619... OK
  Applying dvaapp.0038_auto_20171022_0642... OK
  Applying dvaapp.0039_worker_alive... OK
  Applying dvaapp.0040_tevent_worker... OK
  Applying dvaapp.0041_managementaction_ping_index... OK
  Applying dvaapp.0042_delete_vdnserver... OK
  Applying dvaapp.0043_auto_20171215_1206... OK
  Applying dvaapp.0044_auto_20171222_0539... OK
  Applying dvaapp.0045_auto_20171222_0650... OK
  Applying dvaapp.0046_trainingset... OK
  Applying dvaapp.0047_workerrequest... OK
  Applying dvaapp.0048_auto_20171224_2250... OK
  Applying dvaapp.0049_trainingset_built... OK
  Applying dvaui.0001_initial... OK
  Applying dvaui.0002_auto_20171216_0733... OK
  Applying dvaui.0003_storeddvapql_server... OK
  Applying sessions.0001_initial... OK
Traceback (most recent call last):
  File "./init_fs.py", line 41, in <module>
    dm.download()
  File "/root/DVA/server/dvaapp/models.py", line 232, in download
    fs.get_path_to_file(m['url'],dlpath)
  File "/root/DVA/server/dvaapp/fs.py", line 132, in get_path_to_file
    r = requests.get(path + '?dl=1')
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.dropbox.com', port=443): Max retries exceeded with url: /s/nzz26b2p4wxygg3/coco_mobilenet.pb?dl=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f27a7dee5d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "./start_container.py", line 14, in <module>
    subprocess.check_call(['./init_fs.py',])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./init_fs.py']' returned non-zero exit status 1
Already up-to-date.
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
System check identified some issues:

WARNINGS:
?: (rest_framework.W001) You have specified a default PAGE_SIZE pagination rest_framework setting,without specifying also a DEFAULT_PAGINATION_CLASS.
	HINT: The default for DEFAULT_PAGINATION_CLASS is None. In previous versions this was PageNumberPagination. If you wish to define PAGE_SIZE globally whilst defining pagination_class on a per-view basis you may silence this check.
No changes detected
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
System check identified some issues:

WARNINGS:
?: (rest_framework.W001) You have specified a default PAGE_SIZE pagination rest_framework setting,without specifying also a DEFAULT_PAGINATION_CLASS.
	HINT: The default for DEFAULT_PAGINATION_CLASS is None. In previous versions this was PageNumberPagination. If you wish to define PAGE_SIZE globally whilst defining pagination_class on a per-view basis you may silence this check.
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
Running migrations:
  No migrations to apply.
fatal: unable to access 'https://github.com/akshayubhat/DeepVideoAnalytics/': Failed to connect to github.com port 443: Connection refused
fatal: unable to access 'https://github.com/akshayubhat/DeepVideoAnalytics/': Could not resolve host: github.com
Already up-to-date.
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
System check identified some issues:

WARNINGS:
?: (rest_framework.W001) You have specified a default PAGE_SIZE pagination rest_framework setting,without specifying also a DEFAULT_PAGINATION_CLASS.
	HINT: The default for DEFAULT_PAGINATION_CLASS is None. In previous versions this was PageNumberPagination. If you wish to define PAGE_SIZE globally whilst defining pagination_class on a per-view basis you may silence this check.
No changes detected
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
System check identified some issues:

WARNINGS:
?: (rest_framework.W001) You have specified a default PAGE_SIZE pagination rest_framework setting,without specifying also a DEFAULT_PAGINATION_CLASS.
	HINT: The default for DEFAULT_PAGINATION_CLASS is None. In previous versions this was PageNumberPagination. If you wish to define PAGE_SIZE globally whilst defining pagination_class on a per-view basis you may silence this check.
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
Running migrations:
  No migrations to apply.

**Comment by AKSHAYUBHAT** [comment]
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.dropbox.com', port=443): Max retries exceeded with url: /s/nzz26b2p4wxygg3/coco_mobilenet.pb?dl=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f27a7dee5d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
```

It appears you cannot download models from Dropbox.com 

You should edit /configs/custom_defaults/defaults.py , change the Dropbox.com URLs and
then mount the directory in host OS as a volume at /root/DVA/configs/custom_defaults.
