### ISSUE TITLE
"NameError: global name 'tf' is not defined" on perform_detection task

### ISSUE THREAD

**Issue by YaroslavSchubert** [AKSHAYUBHAT/DeepVideoAnalytics#115]
When I'm trying to analyze simple youtube video the tasks `perform_analysis`, `perform_indexing` and `perform_detection` are failed due to `NameError: global name 'tf' is not defined`.

Sample exception from detection task
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/root/DVA/server/dvaapp/tasks.py", line 247, in perform_detection
    task_handlers.handle_perform_detection(start)
  File "/root/DVA/server/dvaapp/task_handlers.py", line 95, in handle_perform_detection
    detector.load()
  File "/root/DVA/server/dvalib/detector.py", line 131, in load
    self.detection_graph = tf.Graph()
NameError: global name 'tf' is not defined
```

Another question: Is it possible to have a separate branch for a verified version which will definitely work? I'm trying to run for several times for the last month with no luck.

**Comment by AKSHAYUBHAT** [comment]
1. Which compose file are you using cpu / gpu ?

2. Have you pulled latest container images from Docker hub ? 

3. Have you run `git pull` in your host directory from where you launch `docker-compose up`

Due to significant amount of changes (e.g. recent ones added Redis and improved security) its difficult to guarantee and stable release.  I ensure that the Travis CI passes correctly but its not possible to guarantee correctness across all different deployment options. Hopefully in a month the development will stabilize and I will switch semantic versioning the guarantees it provides.

**Comment by AKSHAYUBHAT** [comment]
Closing due to inactivity.
