### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by bartengine27** [AKSHAYUBHAT/DeepVideoAnalytics#130]
the following script

`{
    "tasks": [
        {
            "operation": "perform_indexing",
            "arguments": {
                "map": [
                    {
                        "operation": "perform_retrieval",
                        "arguments": {
                            "count": 20,
                            "retriever_pk": 2
                        }
                    }
                ],
                "target": "query",
                "index": "facenet"
            }
        },
        {
            "operation": "perform_detection",
            "arguments": {
                "map": [
                    {
                        "operation": "perform_analysis",
                        "arguments": {
                            "analyzer": "crnn",
                            "target": "query_regions",
                            "filters": {
                                "event_id": "__parent_event__"
                            }
                        }
                    }
                ],
                "target": "query",
                "detector_pk": 2
            }
        }
    ],
    "image_data_b64": null,
    "process_type": "Q"
}`

failed with

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/root/DVA/server/dvaapp/tasks.py", line 131, in perform_retrieval
    Retrievers.retrieve(start, args.get('retriever_pk', 20), vector, args.get('count', 20))
  File "/root/DVA/server/dvaapp/operations/retrieval.py", line 105, in retrieve
    results = index_retriever.nearest(vector=vector,n=count)
  File "/root/DVA/server/dvalib/retriever.py", line 58, in nearest
    for i, k in enumerate(ranked[:n]):
IndexError: too many indices for array`

**Comment by AKSHAYUBHAT** [comment]
My guess its trying to retrieve faces when there are no faces to retrieve. it should just return empty rather than throwing exception.
