### ISSUE TITLE
mp4 error

### ISSUE THREAD

**Issue by bartengine27** [AKSHAYUBHAT/DeepVideoAnalytics#141]
After uploading an mp4:
`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/root/DVA/server/dvaapp/tasks.py", line 265, in perform_detection
    task_handlers.handle_perform_detection(start)
  File "/root/DVA/server/dvaapp/task_handlers.py", line 97, in handle_perform_detection
    detector.load()
  File "/root/DVA/server/dvalib/detector.py", line 145, in load
    self.session = tf.Session(graph=self.detection_graph,config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1482, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 622, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
InternalError: Failed to create session.
`

**Comment by bartengine27** [comment]
codec issue

first check your mp4 with

`avprobe your.mp4`

If you see the following output at the end

`Unsupported codec with id 0 for input stream 2
Unsupported codec with id 0 for input stream 3`

remove the "offending" streams with

`ffmpeg -i your.mp4 -map 0:0 -map 0:1 -acodec copy -vcodec copy output.mp4`

Note that the command above copies the video and audio stream to output.mp4, 0:2 and 0:3 are *not* removed from your original your.mp4.
