### ISSUE TITLE
dropbox crnn 

### ISSUE THREAD

**Issue by gucasbrg** [AKSHAYUBHAT/DeepVideoAnalytics#142]
```
webserver |   Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
webserver | Running migrations:
webserver |   No migrations to apply.
webserver | Traceback (most recent call last):
webserver |   File "./init_fs.py", line 59, in <module>
webserver |     dm.download()
webserver |   File "/root/DVA/server/dvaapp/models.py", line 274, in download
webserver |     fs.get_path_to_file(m['url'],dlpath)
webserver |   File "/root/DVA/server/dvaapp/fs.py", line 170, in get_path_to_file
webserver |     r = requests.get(path + '?dl=1')
webserver |   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
webserver |     return request('get', url, params=params, **kwargs)
webserver |   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
webserver |     return session.request(method=method, url=url, **kwargs)
webserver |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
webserver |     resp = self.send(prep, **send_kwargs)
webserver |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
webserver |     r = adapter.send(request, **kwargs)
webserver |   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 506, in send
webserver |     raise SSLError(e, request=request)
webserver | requests.exceptions.SSLError: HTTPSConnectionPool(host='www.dropbox.com', port=443): Max retries exceeded with url: /s/l0vo83hmvv2aipn/crnn.pth?dl=1 (Caused by SSLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:590)'),))
```
I use  
```
cd DeepVideoAnalytics/deploy/cpu & docker-compose up
```
If I download this crnn.pth file,Where is the model file placed?

**Comment by AKSHAYUBHAT** [comment]
Retry again it should work. 
You can modify the defaults models file here.

https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/configs/custom_defaults/trained_models.json
