### ISSUE TITLE
Django celery beat is not working correctly

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [AKSHAYUBHAT/DeepVideoAnalytics#143]
```
[2018-02-20 05:16:13,843: CRITICAL/MainProcess] beat raised exception <type 'exceptions.AttributeError'>: AttributeError("'NoneType' object has no attribute 'localize'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/apps/beat.py", line 107, in start_scheduler
    service.start()
  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 528, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 572, in scheduler
    return self.get_scheduler()
  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 567, in get_scheduler
    lazy=lazy,
  File "/usr/local/lib/python2.7/dist-packages/django_celery_beat/schedulers.py", line 183, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 204, in __init__
    self.setup_schedule()
  File "/usr/local/lib/python2.7/dist-packages/django_celery_beat/schedulers.py", line 191, in setup_schedule
    self.install_default_entries(self.schedule)
  File "/usr/local/lib/python2.7/dist-packages/django_celery_beat/schedulers.py", line 290, in schedule
    self._schedule = self.all_as_schedule()
  File "/usr/local/lib/python2.7/dist-packages/django_celery_beat/schedulers.py", line 199, in all_as_schedule
    s[model.name] = self.Entry(model, app=self.app)
  File "/usr/local/lib/python2.7/dist-packages/django_celery_beat/schedulers.py", line 88, in __init__
    model.last_run_at = self._default_now()
  File "/usr/local/lib/python2.7/dist-packages/django_celery_beat/schedulers.py", line 106, in _default_now
    return now.tzinfo.localize(now.replace(tzinfo=None))
AttributeError: 'NoneType' object has no attribute 'localize'
```

**Comment by AKSHAYUBHAT** [comment]
Happened during upgrading container, fixed by pinning specific version of django_celery_beat in requirements.txt in latest commit.
