### ISSUE TITLE
DeepVideoAnalytics starts error

### ISSUE THREAD

**Issue by sunxing109** [AKSHAYUBHAT/DeepVideoAnalytics#144]
![20185725105730](https://user-images.githubusercontent.com/35022475/36637609-bd140178-1a1a-11e8-8bdb-28b5f8ad1610.jpg)

**Comment by sunxing109** [comment]
output of following command
docker exec -it webserver bash -c "cat /root/DVA/logs/beat.log"
shows as follow:
************************************************************************************************************
[2018-02-25 02:55:37,738: INFO/MainProcess] beat: Starting...
[2018-02-25 02:55:37,739: INFO/MainProcess] Writing entries...
[2018-02-25 02:55:37,752: CRITICAL/MainProcess] beat raised exception <type 'exceptions.AttributeError'>: AttributeError("'NoneType' object has no attribute 'localize'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/apps/beat.py", line 107, in start_scheduler
    service.start()
  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 528, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 572, in scheduler
    return self.get_scheduler()
  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 567, in get_scheduler
    lazy=lazy,
  File "/usr/local/lib/python2.7/dist-packages/django_celery_beat/schedulers.py", line 183, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 204, in __init__
    self.setup_schedule()
[2018-02-25 02:55:37,754: WARNING/MainProcess] super(CeleryCommand, self).execute_from_commandline(argv)))
[2018-02-25 02:55:37,754: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 281, in execute_from_commandline
[2018-02-25 02:55:37,754: WARNING/MainProcess] return self.handle_argv(self.prog_name, argv[1:])
[2018-02-25 02:55:37,754: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 480, in handle_argv
[2018-02-25 02:55:37,754: WARNING/MainProcess] return self.execute(command, argv)
[2018-02-25 02:55:37,754: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 412, in execute
[2018-02-25 02:55:37,755: WARNING/MainProcess] ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
[2018-02-25 02:55:37,755: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 285, in run_from_argv
[2018-02-25 02:55:37,755: WARNING/MainProcess] sys.argv if argv is None else argv, command)
[2018-02-25 02:55:37,755: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 368, in handle_argv
[2018-02-25 02:55:37,755: WARNING/MainProcess] return self(*args, **options)
[2018-02-25 02:55:37,755: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 244, in __call__
[2018-02-25 02:55:37,755: WARNING/MainProcess] ret = self.run(*args, **kwargs)
[2018-02-25 02:55:37,755: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/celery/bin/beat.py", line 107, in run
[2018-02-25 02:55:37,755: WARNING/MainProcess] return beat().run()
[2018-02-25 02:55:37,755: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/celery/apps/beat.py", line 79, in run
[2018-02-25 02:55:37,755: WARNING/MainProcess] self.start_scheduler()
[2018-02-25 02:55:37,756: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/celery/apps/beat.py", line 107, in start_scheduler
[2018-02-25 02:55:37,756: WARNING/MainProcess] service.start()
[2018-02-25 02:55:37,756: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 528, in start
[2018-02-25 02:55:37,756: WARNING/MainProcess] humanize_seconds(self.scheduler.max_interval))
[2018-02-25 02:55:37,756: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/kombu/utils/objects.py", line 44, in __get__
[2018-02-25 02:55:37,756: WARNING/MainProcess] value = obj.__dict__[self.__name__] = self.__get(obj)
[2018-02-25 02:55:37,756: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 572, in scheduler
[2018-02-25 02:55:37,756: WARNING/MainProcess] return self.get_scheduler()
[2018-02-25 02:55:37,756: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 567, in get_scheduler
[2018-02-25 02:55:37,756: WARNING/MainProcess] lazy=lazy,
[2018-02-25 02:55:37,757: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/django_celery_beat/schedulers.py", line 183, in __init__
[2018-02-25 02:55:37,757: WARNING/MainProcess] Scheduler.__init__(self, *args, **kwargs)
[2018-02-25 02:55:37,757: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 204, in __init__
[2018-02-25 02:55:37,757: WARNING/MainProcess] self.setup_schedule()
[2018-02-25 02:55:37,757: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/django_celery_beat/schedulers.py", line 191, in setup_schedule
[2018-02-25 02:55:37,757: WARNING/MainProcess] self.install_default_entries(self.schedule)
[2018-02-25 02:55:37,757: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/django_celery_beat/schedulers.py", line 290, in schedule
[2018-02-25 02:55:37,757: WARNING/MainProcess] self._schedule = self.all_as_schedule()
[2018-02-25 02:55:37,757: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/django_celery_beat/schedulers.py", line 199, in all_as_schedule
[2018-02-25 02:55:37,757: WARNING/MainProcess] s[model.name] = self.Entry(model, app=self.app)
[2018-02-25 02:55:37,757: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/django_celery_beat/schedulers.py", line 88, in __init__
[2018-02-25 02:55:37,757: WARNING/MainProcess] model.last_run_at = self._default_now()
[2018-02-25 02:55:37,758: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/django_celery_beat/schedulers.py", line 106, in _default_now
[2018-02-25 02:55:37,758: WARNING/MainProcess] return now.tzinfo.localize(now.replace(tzinfo=None))
[2018-02-25 02:55:37,758: WARNING/MainProcess] AttributeError
[2018-02-25 02:55:37,758: WARNING/MainProcess] :
[2018-02-25 02:55:37,758: WARNING/MainProcess] 'NoneType' object has no attribute 'localize'
[2018-02-25 02:55:37,758: INFO/MainProcess] Writing entries...
*******************************************************************************************************

**Comment by AKSHAYUBHAT** [comment]
This is same as this one: https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/issues/143

I fixed it by selecting a specific older version of django_celery_beat, if you are using container image you should not have this error. If you have built your own image, update the requirements.txt and rebuild the container.
