### ISSUE TITLE
InternalError: Failed to create session. 

### ISSUE THREAD

**Issue by sunxing109** [AKSHAYUBHAT/DeepVideoAnalytics#152]
After viewing the video upload task failed, the error message is as follows 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/root/DVA/server/dvaapp/tasks.py", line 59, in perform_indexing
    sync = task_handlers.handle_perform_indexing(start)
  File "/root/DVA/server/dvaapp/task_handlers.py", line 47, in handle_perform_indexing
    indexing.Indexers.index_queryset(di, visual_index, start, target, queryset)
  File "/root/DVA/server/dvaapp/operations/indexing.py", line 53, in index_queryset
    visual_index.load()
  File "/root/DVA/server/dvalib/indexer.py", line 110, in load
    self.session = tf.InteractiveSession(config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1612, in __init__
    super(InteractiveSession, self).__init__(target, graph, config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 622, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
InternalError: Failed to create session.

**Comment by AKSHAYUBHAT** [comment]
looks like an error related to Tensorflow not being able to create a session. Are you using a GPU? 

https://github.com/tensorflow/tensorflow/issues/9549

This could also be due to AVX extension in TF 1.6 in case you have upgraded to latest containers. 
But in that case it would be illegal instruction if your CPU did not have AVX instruction set. 

Maybe try restarting. However it does not looks like error with video upload since the error happens inside indexer.py.

**Comment by AKSHAYUBHAT** [comment]
closed due to inactivity

**Comment by dakshvar22** [comment]
Even I am facing the same issue. I am using a GPU and using docker-compose-gpu.yml file to start the containers.

**Comment by AKSHAYUBHAT** [comment]
- Which GPU and How much GPU memory do you have?

- Are you running?
`./manage.py start gpu` 

I typically test on P100s on GCP.

**Comment by dakshvar22** [comment]
I am running on GTX 1080, 11 GB memory .

I ran the containers by going into deploy/gpu, creating a copy of docker-compose-gpu.yml as docker-compose.yml and then running - 

`nvidia-docker-compose up`

**Comment by AKSHAYUBHAT** [comment]
Which version of nvidia-docker do you have? 
Nvidia-docker recently upgraded to version 2.0 which does not requires 
"nvidia-docker-compose". Rather you need to specify nvidia-docker as a default 
docker runtime and use the normal docker-compose.

**Comment by AKSHAYUBHAT** [comment]
The compose files i support latest version of nvidia-docker.
https://github.com/NVIDIA/nvidia-docker

**Comment by dakshvar22** [comment]
Resolved the issue. It was an nvidia driver issue. The driver installed was not compatible with CUDA 9, which came with the base image in the dockerfile.

**Comment by AKSHAYUBHAT** [comment]
@dakshvar22 Thanks for solving this!
