### ISSUE TITLE
Region matching query does not exist

### ISSUE THREAD

**Issue by sunxing109** [AKSHAYUBHAT/DeepVideoAnalytics#153]
When I search for pictures, two processes have different errors

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/root/DVA/server/dvaapp/tasks.py", line 131, in perform_retrieval
    Retrievers.retrieve(start, args.get('retriever_pk', 20), vector, args.get('count', 20))
  File "/root/DVA/server/dvaapp/operations/retrieval.py", line 114, in retrieve
    dd = Region.objects.get(pk=r['detection_primary_key'])
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Region matching query does not exist.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/root/DVA/server/dvaapp/tasks.py", line 131, in perform_retrieval
    Retrievers.retrieve(start, args.get('retriever_pk', 20), vector, args.get('count', 20))
  File "/root/DVA/server/dvaapp/operations/retrieval.py", line 123, in retrieve
    qr.save()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 223, in __exit__
    connection.commit()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 262, in commit
    self._commit()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 236, in _commit
    return self.connection.commit()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 236, in _commit
    return self.connection.commit()
IntegrityError: insert or update on table "dvaapp_queryresults" violates foreign key constraint "dvaapp_queryresults_frame_id_89cf9f17_fk_dvaapp_frame_id"
DETAIL:  Key (frame_id)=(377) is not present in table "dvaapp_frame".

**Comment by AKSHAYUBHAT** [comment]
Did you import a video/dataset? In both cases it appears that the primary_key does not exists in the database. 

The only place where this mismatch (between value stored in json file along with the index) can occur is during import. 

I will check later today if video/dataset import from export code has any bugs.

**Comment by AKSHAYUBHAT** [comment]
cannot reproduce / confirm.
