### ISSUE TITLE
Cannot access Web UI

### ISSUE THREAD

**Issue by thesunkid19** [AKSHAYUBHAT/DeepVideoAnalytics#179]
Thank you for your 
- Have you verified that docker is installed correctly and e.g. GFW is not preventing downloads?
No problem

- Which docker-compose.yml file are you using?
docker-compose-dev.yaml

- Please post output of `docker ps -a` or confirm that all containers are running?
`CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                        PORTS                                                        NAMES
bd33086b8a72        akshayubhat/dva-auto:latest   "bash -c 'cd /root/D…"   19 minutes ago      Up 23 seconds                 6006/tcp, 127.0.0.1:8000->80/tcp, 127.0.0.1:8889->8888/tcp   webserver
d5b2f2574ba3        bitnami/redis:latest          "/app-entrypoint.sh …"   19 minutes ago      Up 19 minutes                 6379/tcp                                                     dva-redis
c322c29180db        postgres:9.6.6                "docker-entrypoint.s…"   19 minutes ago      Up 19 minutes                 5432/tcp                                                     dva-pg
06fcb6e2b3f9        rabbitmq                      "docker-entrypoint.s…"   19 minutes ago      Up 19 minutes                 4369/tcp, 5671-5672/tcp, 25672/tcp                           dva-rmq
9897c60d9050        akshayubhat/dva-auto:latest   "/run_jupyter.sh --a…"   27 minutes ago      Exited (255) 19 minutes ago   80/tcp, 6006/tcp, 8888/tcp, 0.0.0.0:8890->8890/tcp           elated_williams
b0ffde7e74a2        akshayubhat/dva-auto:latest   "/run_jupyter.sh --a…"   28 minutes ago      Created                                                                                    dreamy_bardeen
ee3b98ae6c57        akshayubhat/dva-auto:latest   "bash -c 'wget dropb…"   3 hours ago         Exited (0) 3 hours ago                                                                     ecstatic_tesla
c6f33fca6ce5        akshayubhat/dva-auto:latest   "bash"                   7 hours ago         Exited (255) 19 minutes ago   80/tcp, 6006/tcp, 0.0.0.0:8888->8888/tcp                     peaceful_elbakyan
8fc44da04f22        hello-world                   "/hello"                 9 hours ago         Exited (0) 9 hours ago                                                                     mystifying_lovelac`

- If a specific container is not running or "exited" please post output of `docker logs <name of the container>` No 

- Is your question about OCR blog post in notebooks/OCR/ ? No

I reset by './dvactl clean && ./dvactl start' many times but can't to access Web API as localhost:8000 or localhost:8888. I use both cpu and dev mode.

**Comment by AKSHAYUBHAT** [comment]
```
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                        PORTS                                                        NAMES
bd33086b8a72        akshayubhat/dva-auto:latest   "bash -c 'cd /root/D…"   19 minutes ago      Up 23 seconds                 6006/tcp, 127.0.0.1:8000->80/tcp, 127.0.0.1:8889->8888/tcp   webserver
d5b2f2574ba3        bitnami/redis:latest          "/app-entrypoint.sh …"   19 minutes ago      Up 19 minutes                 6379/tcp                                                     dva-redis
c322c29180db        postgres:9.6.6                "docker-entrypoint.s…"   19 minutes ago      Up 19 minutes                 5432/tcp                                                     dva-pg
06fcb6e2b3f9        rabbitmq                      "docker-entrypoint.s…"   19 minutes ago      Up 19 minutes                 4369/tcp, 5671-5672/tcp, 25672/tcp                           dva-rmq
9897c60d9050        akshayubhat/dva-auto:latest   "/run_jupyter.sh --a…"   27 minutes ago      Exited (255) 19 minutes ago   80/tcp, 6006/tcp, 8888/tcp, 0.0.0.0:8890->8890/tcp           elated_williams
b0ffde7e74a2        akshayubhat/dva-auto:latest   "/run_jupyter.sh --a…"   28 minutes ago      Created                                                                                    dreamy_bardeen
ee3b98ae6c57        akshayubhat/dva-auto:latest   "bash -c 'wget dropb…"   3 hours ago         Exited (0) 3 hours ago                                                                     ecstatic_tesla
c6f33fca6ce5        akshayubhat/dva-auto:latest   "bash"                   7 hours ago         Exited (255) 19 minutes ago   80/tcp, 6006/tcp, 0.0.0.0:8888->8888/tcp                     peaceful_elbakyan
8fc44da04f22        hello-world                   "/hello"                 9 hours ago         Exited (0) 9 hours ago                                                                     mystifying_lovelac
```

**Comment by AKSHAYUBHAT** [comment]
I reformatted your docker ps -a output. It appears that the webserver container is running but it was "Up" for only 23 seconds (i.e. at the time you ran command), it should take couple of more minutes to start webserver after downloading all the models. 

How much memory/RAM does your machine have? After upgrading to TF 1.8 DVA requires at least ~10 gb RAM.  

Finally since the webserver is running you can simply shell into it by running `./dvactl shell`. 
And look at the output of `docker logs webserver` to see where it's stuck.

**Comment by thesunkid19** [comment]
Thank you sir!
I used a Macbook 16gb RAM to run it. 
I waited and runned several times but It can't help. When I run `docker logs webserver`, the output is:

> running build_ext
building 'lib.utils.bbox' extension
creating build
creating build/temp.linux-x86_64-2.7
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c bbox.c -o build/temp.linux-x86_64-2.7/bbox.o
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1777:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:18,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from bbox.c:567:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
creating /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib
creating /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib/utils
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/bbox.o -o /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib/utils/bbox.so
building 'lib.utils.cython_nms' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cython_nms.c -o build/temp.linux-x86_64-2.7/cython_nms.o
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1777:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:18,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from cython_nms.c:567:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/cython_nms.o -o /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib/utils/cython_nms.so
Collecting django-debug-toolbar
  Downloading https://files.pythonhosted.org/packages/b2/ff/eb95539d31b3f3c12803c8f18cefe7f9e6f7281b059a36dbc9ee9b52c558/django_debug_toolbar-1.9.1-py2.py3-none-any.whl (206kB)
Requirement already satisfied: Django>=1.8 in /usr/local/lib/python2.7/dist-packages (from django-debug-toolbar) (1.11.3)
Collecting sqlparse>=0.2.0 (from django-debug-toolbar)
  Downloading https://files.pythonhosted.org/packages/65/85/20bdd72f4537cf2c4d5d005368d502b2f464ede22982e724a82c86268eda/sqlparse-0.2.4-py2.py3-none-any.whl
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from Django>=1.8->django-debug-toolbar) (2018.4)
keras 2.2.0 requires keras-applications==1.0.2, which is not installed.
keras 2.2.0 requires keras-preprocessing==1.0.1, which is not installed.
Installing collected packages: sqlparse, django-debug-toolbar
Successfully installed django-debug-toolbar-1.9.1 sqlparse-0.2.4
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
No changes detected
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying django_celery_beat.0001_initial... OK
  Applying django_celery_beat.0002_auto_20161118_0346... OK
  Applying django_celery_beat.0003_auto_20161209_0049... OK
  Applying django_celery_beat.0004_auto_20170221_0000... OK
  Applying django_celery_results.0001_initial... OK
  Applying dvaapp.0001_initial... OK
  Applying dvaapp.custom_migration... OK
  Applying dvaui.0001_initial... OK
  Applying dvaui.0002_auto_20171216_0733... OK
  Applying dvaui.0003_storeddvapql_server... OK
  Applying sessions.0001_initial... OK
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Cloning into 'VDN'...

And then I run `docker ps -a`, the `webserver` had existed 1 minute ago in STATUS.  Then I run `docker-compose -f deploy/compose/docker-compose-dev.yaml up`, `webserver` up again but can't help to access webserver  as http://localhost:8888; at the last of `docker-compose -f deploy/compose/docker-compose-dev.yaml up`'s output:

>  webserver | Traceback (most recent call last):
webserver |   File "./launch_from_env.py", line 70, in <module>
webserver |     subprocess.check_output(["python", "manage.py", "collectstatic", "--no-input"])
webserver |   File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
webserver |     raise CalledProcessError(retcode, cmd, output=output)
webserver | subprocess.CalledProcessError: Command '['python', 'manage.py', 'collectstatic', '--no-input']' returned non-zero exit status -9

**Comment by AKSHAYUBHAT** [comment]
I recommend using following command to restart. 

`./dvactl clean && ./dvactl start`

This command ensures that the volumes are cleaned. Otherwise artifacts from previous runs can cause issues. E.g. my guess as to why collectstatic failed is due to files from previous run causing issues. 

Finally Docker on Mac OSX has setting that lets you specify amount of max memory limit.
You might need to change it. 

![screen shot 2018-06-24 at 10 45 46 pm](https://user-images.githubusercontent.com/35259/41832343-86a2b3c0-7800-11e8-886f-0f5e048c50b0.png)
