### ISSUE TITLE
GPU config issue

### ISSUE THREAD

**Issue by thesunkid19** [AKSHAYUBHAT/DeepVideoAnalytics#180]
When I attemp to configure to use GPU, it threw some errors. I guess these problems come from your last edit yml file to yaml.
Here is the error when I configure GPU and run `./dvactl start`

> Traceback (most recent call last):
  File "./dvactl", line 337, in <module>
    gpu_config=mode_dict['gpu_config'])
  File "/Users/thesunkid/Desktop/thinh/DeepVideoAnalytics/deploy/compose/__init__.py", line 124, in handle_compose_operations
    generate_multi_gpu_compose(gpu_compose_filename, gpu_config)
  File "/Users/thesunkid/Desktop/thinh/DeepVideoAnalytics/deploy/compose/__init__.py", line 20, in generate_multi_gpu_compose
    file('compose/gpu_cpu_block.yaml').read().format(worker_name=worker_name, env_key=env_key, env_value=1))
IOError: [Errno 2] No such file or directory: 'compose/gpu_cpu_block.yaml'

I fixed it by adding the path DIR before this format. But another comes out:

> Traceback (most recent call last):
  File "./dvactl", line 337, in <module>
    gpu_config=mode_dict['gpu_config'])
  File "/Users/thesunkid/Desktop/thinh/DeepVideoAnalytics/deploy/compose/__init__.py", line 129, in handle_compose_operations
    generate_multi_gpu_compose(gpu_compose_filename, gpu_config)
  File "/Users/thesunkid/Desktop/thinh/DeepVideoAnalytics/deploy/compose/__init__.py", line 26, in generate_multi_gpu_compose
    with open(fname, 'w') as out:
IOError: [Errno 2] No such file or directory: u'deploy/compose/gpu/docker-compose-1-gpus.yml'

This dir actually don't exist so I guest that come from previous fix.

**Comment by AKSHAYUBHAT** [comment]
Fixed in latest commit, run `./dvactl configure`.
Note that I am currently in processing of changing the underlying data model significantly.

**Comment by thesunkid19** [comment]
A trival issue, in `deploy/compose/__init__.py` file, `fname = '/docker-compose-{}-gpus.yaml'` need to correct to `fname = '/docker-compose-{}-gpus.yml'`
