### ISSUE TITLE
cant access local server in dev mode

### ISSUE THREAD

**Issue by rastinrastini** [AKSHAYUBHAT/DeepVideoAnalytics#209]
Hi
where is problem?
when run in dev mode i cant access server in localhost:80 address and after 20 min get error
this is export of comman "sudo docker ps -a"
![image](https://user-images.githubusercontent.com/7768900/45286132-3e9b7800-b4fa-11e8-9fed-1230a92b153d.png)

this is error after waiting few minutes
![image](https://user-images.githubusercontent.com/7768900/45286208-71457080-b4fa-11e8-8962-e38194d6ce9b.png)

**Comment by bmabir17** [comment]
your docker container exits after some time. can you run it in cpu or gpu mode?
If not then try
`
./dvactl clean
`
then
`
./dvactl start
`

**Comment by rastinrastini** [comment]
when docker is run i cant access to it
how can access to it?
localhost doesnt work

**Comment by AKSHAYUBHAT** [comment]
Can you post output of ‘./dvactl logs webserver’ that will contain real reason as to why the container exited

**Comment by rastinrastini** [comment]
this command dont work. throws error:
`(p2env) rastin@rastin-N551JQ:~/Desktop/projects/visual_search_2/deep2/deepvideoanalytics$ sudo ./dvactl logs webserver
[sudo] password for rastin: 
usage: dvactl [-h] [-f F] [--container CONTAINER] [--pod POD] action
dvactl: error: unrecognized arguments: webserver
`

**Comment by AKSHAYUBHAT** [comment]
Oh sorry “docker logs webserver”

**Comment by rastinrastini** [comment]
`(p2env) rastin@rastin-N551JQ:~/Desktop/projects/visual_search_2/deep2/deepvideoanalytics/logs$ sudo docker logs webserver
running build_ext
building 'lib.utils.bbox' extension
creating build
creating build/temp.linux-x86_64-2.7
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c bbox.c -o build/temp.linux-x86_64-2.7/bbox.o
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1777:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:18,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from bbox.c:567:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
creating /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib
creating /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib/utils
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/bbox.o -o /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib/utils/bbox.so
building 'lib.utils.cython_nms' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cython_nms.c -o build/temp.linux-x86_64-2.7/cython_nms.o
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1777:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:18,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from cython_nms.c:567:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/cython_nms.o -o /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib/utils/cython_nms.so
Collecting django-debug-toolbar
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/django-debug-toolbar/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/django-debug-toolbar/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/django-debug-toolbar/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/django-debug-toolbar/
  Downloading https://files.pythonhosted.org/packages/b5/c8/e1db2adae36a02f91e1e4ba132a287ba1f803cd3840064a628a0836aa2fc/django_debug_toolbar-1.10-py2.py3-none-any.whl (206kB)
Collecting sqlparse>=0.2.0 (from django-debug-toolbar)
  Downloading https://files.pythonhosted.org/packages/65/85/20bdd72f4537cf2c4d5d005368d502b2f464ede22982e724a82c86268eda/sqlparse-0.2.4-py2.py3-none-any.whl
Requirement already satisfied: Django>=1.11 in /usr/local/lib/python2.7/dist-packages (from django-debug-toolbar) (1.11.3)
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from Django>=1.11->django-debug-toolbar) (2018.5)
Installing collected packages: sqlparse, django-debug-toolbar
Successfully installed django-debug-toolbar-1.10 sqlparse-0.2.4
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
Migrations for 'dvaapp':
  dvaapp/migrations/0001_initial.py
    - Create model DeletedVideo
    - Create model DVAPQL
    - Create model Export
    - Create model Frame
    - Create model HyperRegionRelation
    - Create model HyperTubeRegionRelation
    - Create model IndexEntries
    - Create model ManagementAction
    - Create model QueryRegion
    - Create model QueryResult
    - Create model Region
    - Create model RegionRelation
    - Create model Retriever
    - Create model Segment
    - Create model SystemState
    - Create model TaskRestart
    - Create model TEvent
    - Create model TrainedModel
    - Create model TrainingSet
    - Create model Tube
    - Create model TubeRegionRelation
    - Create model TubeRelation
    - Create model Video
    - Create model Worker
    - Add field video to tuberelation
    - Add field video to tuberegionrelation
    - Add field video to tube
    - Add field training_set to trainedmodel
    - Add field training_set to tevent
    - Add field video to tevent
    - Add field worker to tevent
    - Add field event to segment
    - Add field video to segment
    - Add field event to regionrelation
    - Add field source_region to regionrelation
    - Add field target_region to regionrelation
    - Add field video to regionrelation
    - Add field event to region
    - Add field user to region
    - Add field video to region
    - Add field region to queryresult
    - Add field retrieval_event to queryresult
    - Add field tube to queryresult
    - Add field video to queryresult
    - Add field event to queryregion
    - Add field query to queryregion
    - Add field event to indexentries
    - Add field video to indexentries
    - Add field event to hypertuberegionrelation
    - Add field tube to hypertuberegionrelation
    - Add field video to hypertuberegionrelation
    - Add field event to hyperregionrelation
    - Add field region to hyperregionrelation
    - Add field video to hyperregionrelation
    - Add field event to frame
    - Add field video to frame
    - Add field event to export
    - Alter unique_together for tuberelation (1 constraint(s))
    - Alter unique_together for tuberegionrelation (1 constraint(s))
    - Alter unique_together for tube (1 constraint(s))
    - Alter unique_together for segment (1 constraint(s))
    - Alter unique_together for regionrelation (1 constraint(s))
    - Alter unique_together for region (1 constraint(s))
    - Alter unique_together for hypertuberegionrelation (1 constraint(s))
    - Alter unique_together for hyperregionrelation (1 constraint(s))
    - Alter unique_together for frame (1 constraint(s))
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying django_celery_beat.0001_initial... OK
  Applying django_celery_beat.0002_auto_20161118_0346... OK
  Applying django_celery_beat.0003_auto_20161209_0049... OK
  Applying django_celery_beat.0004_auto_20170221_0000... OK
  Applying django_celery_results.0001_initial... OK
  Applying dvaapp.0001_initial... OK
  Applying dvaapp.custom_migration... OK
  Applying dvaui.0001_initial... OK
  Applying dvaui.0002_auto_20171216_0733... OK
  Applying dvaui.0003_storeddvapql_server... OK
  Applying sessions.0001_initial... OK
Cloning into 'VDN'...
Traceback (most recent call last):
  File "./launch_from_env.py", line 115, in <module>
    launch_model_queue(k)
  File "./launch_from_env.py", line 22, in launch_model_queue
    queue_name = 'q_retriever_{}'.format(dm.pk)
AttributeError: 'NoneType' object has no attribute 'pk'
Traceback (most recent call last):
  File "./start_container.py", line 18, in <module>
    subprocess.check_call(['./launch_from_env.py','0'])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./launch_from_env.py', '0']' returned non-zero exit status 1
`

**Comment by AKSHAYUBHAT** [comment]
It appears that the model files have not been downloaded correctly as a result the retriever cannot be created. 

“
Traceback (most recent call last): File "./launch_from_env.py", line 115, in <module> launch_model_queue(k) File "./launch_from_env.py", line 22, in launch_model_queue queue_name = 'q_retriever_{}'.format(dm.pk) AttributeError: 'NoneType' object has no attribute 'pk' Traceback (most recent call last): File "./start_container.py", line 18, in <module>

**Comment by rastinrastini** [comment]
now what must do and how correct it?

**Comment by AKSHAYUBHAT** [comment]
Are you running behind GFW or some other firewall that intercepts connections preventing model weights from being downloaded from Dropbox, Digital Ocean spaces ?

Here are the instructions in that case: 
https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/docs/gfw.md

**Comment by rastinrastini** [comment]
i download models locally and set "trained_models_local.json"

**Comment by roger-zhao** [comment]
@rastinrastini You have to make sure all trained models need to be put into a directory named "models" which is located in root of codebase, then try with dev mode and dedicate the init_models to "trained_models_local.json"

**Comment by AKSHAYUBHAT** [comment]
closing due to inactivity
