### ISSUE TITLE
NameError: global name 'analyzer' is not defined

### ISSUE THREAD

**Issue by helium390** [AKSHAYUBHAT/DeepVideoAnalytics#223]
When I change url of crnn it downloads and the log gives me the error:

`
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/root/DVA/server/dvaapp/tasks.py", line 338, in perform_analysis
    task_handlers.handle_perform_analysis(dt)
  File "/root/DVA/server/dvaapp/task_handlers.py", line 141, in handle_perform_analysis
    analysis.Analyzers.load_analyzer(da)
  File "/root/DVA/server/dvaapp/operations/analysis.py", line 21, in load_analyzer
    Analyzers._analyzers[da.name] = analyzer.OpenImagesAnnotator(aroot + "{}/open_images.ckpt".format(da.uuid))
NameError: global name 'analyzer' is not defined
`
What am I doing wrong?

**Comment by AKSHAYUBHAT** [comment]
This typically means that "/server/davalib/analyzer.py" could not be loaded. 
Did you by change modify that file? 

Can you manually enter into a shell 
by running 
`./dvactl shell` 
followed by 
`python manage.py shell`
and then try importing the package
`from dvalib import analyzer`

Also you are saying that you changed the url for CRNN model however this error appears on the line for `OpenImagesAnnotator` model. 

If you want to use CRNN model for a custom language, e.g. Korean, you will currently need to change the code (since it needs a list of characters). I am hoping to put that config in model spec json inside arguments . 

I currently only have English CRNN model, but I am looking for a CRNN model for another language so that the code is more robust, and issue like the one you are facing dont appear. 
https://github.com/YoungMiao/crnn

**Comment by helium390** [comment]
Yes. In analyzer.py I missed to add `#coding:UTF-8` . And now I'm getting the log error `AttributeError: 'CRNNAnnotator' object has no attribute 'transformer'`: 

`
[2018-10-14 10:04:02,258: INFO/MainProcess] Received task: perform_analysis[d91b0e08-9d7d-4ddc-8251-5e00590b16e3]  
[2018-10-14 10:04:02,304: ERROR/MainProcess] Task perform_analysis[d91b0e08-9d7d-4ddc-8251-5e00590b16e3] raised unexpected: AttributeError("'CRNNAnnotator' object has no attribute 'transformer'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/root/DVA/server/dvaapp/tasks.py", line 338, in perform_analysis
    task_handlers.handle_perform_analysis(dt)
  File "/root/DVA/server/dvaapp/task_handlers.py", line 195, in handle_perform_analysis
    object_name, text, metadata, _ = analyzer.apply(path)
  File "/root/DVA/server/dvalib/analyzer.py", line 142, in apply
    image = self.transformer(image)
AttributeError: 'CRNNAnnotator' object has no attribute 'transformer'
`

**Comment by AKSHAYUBHAT** [comment]
Technically apply should `load` the model where the transformer gets set in analyzer.py . 

```
    def load(self):
        logging.info("Loding CRNN model first apply will be slow")
        if torch.cuda.is_available():
            self.session = crnn_model.CRNN(32, 1, 37, 256, 1).cuda()
            self.cuda = True
        else:
            self.session = crnn_model.CRNN(32, 1, 37, 256, 1)
        self.session.load_state_dict(torch.load(self.model_path))
        self.session.eval()
        self.converter = utils.strLabelConverter(self.alphabet)
        self.transformer = dataset.resizeNormalize((100, 32))
```

Give me a day, I am planning to add the Chinese pretrained model also make a single interface across all models.

**Comment by helium390** [comment]
Okay.
In my case `self.session = crnn_model.CRNN(32, 1, **num**, 256, 1)`, where **num = len(alphabet)**

**Comment by AKSHAYUBHAT** [comment]
Yes Ideally that should be defined in model JSON and should be loaded from there. Having more than one language should root out these bugs
