### ISSUE TITLE
run server/migrate.sh problem

### ISSUE THREAD

**Issue by ShaoDu** [AKSHAYUBHAT/DeepVideoAnalytics#227]
when I run server/maigrate.sh,this problem occur.
can you see this problems ?

Traceback (most recent call last):
  File "server/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/lf/anaconda3/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/lf/anaconda3/lib/python3.6/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/home/lf/anaconda3/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/lf/anaconda3/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/lf/anaconda3/lib/python3.6/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/home/lf/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lf/桌面/DeepVideoAnalytics-master3/server/dvaapp/models.py", line 7, in <module>
    from django.contrib.auth.models import User
  File "/home/lf/anaconda3/lib/python3.6/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/lf/anaconda3/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/lf/anaconda3/lib/python3.6/site-packages/django/db/models/base.py", line 110, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/lf/anaconda3/lib/python3.6/site-packages/django/apps/registry.py", line 247, in get_containing_app_config
    self.check_apps_ready()
  File "/home/lf/anaconda3/lib/python3.6/site-packages/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by AKSHAYUBHAT** [comment]
Sorry i cannot support any workflow that run outside the container since there is significant effort required to make sure that all settings and packages are set correctly.

**Comment by ShaoDu** [comment]
You means it can only work on docker?

**Comment by ShaoDu** [comment]
This error is generated by running on the pycharm terminal.So I have to operate in a docker container to be able to do that. Right?
