### ISSUE TITLE
While running CPU- docker getting following error

### ISSUE THREAD

**Issue by kumarneeraj2005** [AKSHAYUBHAT/DeepVideoAnalytics#24]
youtube-dl is up-to-date (2017.04.11)
Already up-to-date.
libdc1394 error: Failed to initialize libdc1394
WARNING:root:Could not import torch
No changes detected
libdc1394 error: Failed to initialize libdc1394
WARNING:root:Could not import torch
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, djcelery, dvaapp, sessions
Running migrations:
  Applying dvaapp.0002_s3_export... OK
  Applying dvaapp.0003_auto_20170412_0733... OK
[localhost] local: sleep 20
[localhost] local: python manage.py makemigrations
[localhost] local: python manage.py migrate
[localhost] local: fab startq:qdetector &
[localhost] local: fab startq:qfaceretriever &
[localhost] local: fab startq:qextract &
[localhost] local: fab startq:qretriever &
[localhost] local: fab startq:qfacedetector &
[localhost] local: fab startq:qindexer &
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 756, in main
    *args, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 426, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/root/DVA/fabfile.py", line 56, in start_container
    launch_queues_env()
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 170, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/root/DVA/fabfile.py", line 253, in launch_queues_env
    if VDNServer.objects.count() == 0:
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 363, in count
    return self.query.get_count(using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 498, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 479, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "dvaapp_vdnserver" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "dvaapp_vdnserver"
                                          ^
2017-04-12T18:30:38.907690329Z 
youtube-dl is up-to-date (2017.04.11)
Already up-to-date.
libdc1394 error: Failed to initialize libdc1394
WARNING:root:Could not import torch
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/makemigrations.py", line 110, in handle
    loader.check_consistent_history(connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 282, in check_consistent_history
    applied = recorder.applied_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "db" to address: Name or service not known
2017-04-12T18:40:17.932230421Z 
[localhost] local: sleep 20
[localhost] local: python manage.py makemigrations
2017-04-12T18:40:18.112433772Z 
Fatal error: local() encountered an error (return code 1) while executing 'python manage.py makemigrations'
2017-04-12T18:40:18.112490298Z 
Aborting.

**Comment by AKSHAYUBHAT** [comment]
Looks like it cannot find the database container. Did you use docker-compose, which yml file did you use?

**Comment by kumarneeraj2005** [comment]
i simply did 
git clone https://github.com/AKSHAYUBHAT/DeepVideoAnalytics
cd DeepVideoAnalytics/docker && docker-compose up
 and getting above exception.
My OS is MAC, recent updated version of Docker.

**Comment by AKSHAYUBHAT** [comment]
How much memory do you have? 

can you run 
` 
cd DeepVideoAnalytics/docker 
docker-compose down -v
./rebuild.sh
docker-compose up 
`
once its up run in another terminal
`
docker ps -a
`
it should show you all three containers running.

**Comment by kumarneeraj2005** [comment]
Increased memory to 16 GB and executed rebuild command,now its up and working.
Thanks a lot.
