### ISSUE TITLE
facenet issue...

### ISSUE THREAD

**Issue by rap9430** [AKSHAYUBHAT/DeepVideoAnalytics#43]
After uploading an image (the one with Di Caprio's face) i get the following error in the corresponding log file. I'd appreciate any insight.

[2017-06-07 19:01:37,824: ERROR/MainProcess] Task facenet_query_by_image[391ce749-e7e7-4395-865d-28f3cdb4401b] raised unexpected: AttributeError("'NoneType' object has no attribute 'shape'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/root/DVA/dvaapp/tasks.py", line 341, in facenet_query_by_image
    results = Q.find(dq.count)
  File "/root/DVA/dvalib/entity.py", line 26, in find
    results[self.visual_index.name] = self.visual_index.nearest(image_path=self.local_path,n=n)
  File "/root/DVA/dvalib/indexer.py", line 47, in nearest
    for k in xrange(self.index.shape[0]):
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by AKSHAYUBHAT** [comment]
The error shows that you do not have any facenet vectors to match against. (I will improve the exception message)

Have you "imported" the Labeled Faces in the Wild from VDN on sidebar.  Or added your own images/videos. In the latter case it might take few minutes for feature computations to finish. You can see the curent Index vectors on Indexes page from the sidebar.

**Comment by rap9430** [comment]
Solved. Thanks for the quick response. I downloaded lfw and everything works fine.
