### ISSUE TITLE
Error when do the searching ...

### ISSUE THREAD

**Issue by paulxiong** [AKSHAYUBHAT/DeepVideoAnalytics#61]
here is the err log when hit searching :dva-server | Internal Server Error: /Search
dva-server | Traceback (most recent call last):
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
dva-server |     response = get_response(request)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
dva-server |     response = self.process_exception_by_middleware(e, request)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
dva-server |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
dva-server |     return view_func(request, *args, **kwargs)
dva-server |   File "/root/DVA/dvaapp/views.py", line 398, in search
dva-server |     qp.wait()
dva-server |   File "/root/DVA/dvaapp/operations/query_processing.py", line 301, in wait
dva-server |     raise ValueError(e)

**Comment by AKSHAYUBHAT** [comment]
can you share the contents of the log qretriever.log or qfaceretriever.log ? 
You should be able to see the actual error that was encountered by the task performing indexing or retrieval their. The dva-server logs merely show that the underlying tasks has hit an error.

The design of how queries are processed is being changed.

**Comment by paulxiong** [comment]
qretriever.log and qfaceretriever.log are located in etc/log? I did not find them.

**Comment by AKSHAYUBHAT** [comment]
They are stored in DeepVideoAnalytics/logs/  . You can view them through the webapp directly by going to <address>/status .

**Comment by paulxiong** [comment]
logs/qfaceretriever.log
......
[2017-08-01 20:26:08,923: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:10,046: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:11,251: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:12,420: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:13,645: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:14,952: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:19,657: INFO/MainProcess] missed heartbeat from celery@qindexer.d285b752c875
[2017-08-01 20:26:30,917: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:32,042: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:33,276: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:34,413: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:35,555: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:36,933: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:38,055: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:41,034: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:42,178: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:43,434: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:44,572: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:49,666: INFO/MainProcess] missed heartbeat from celery@qindexer.d285b752c875
[2017-08-01 20:27:02,100: INFO/MainProcess] Received task: perform_indexing[9874f950-de32-4d59-8de5-86e96e925401]  
[2017-08-01 20:27:03,178: WARNING/MainProcess] Loading facenet , first apply / query will be slower
[2017-08-01 20:27:20,375: WARNING/MainProcess] Creating a session facenet , first apply / query will be slower

**Comment by paulxiong** [comment]
logs/qretriever.log

[2017-08-01 20:26:35,537: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:36,936: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:38,057: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:41,035: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:42,179: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:43,436: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:44,569: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:26:51,819: INFO/MainProcess] missed heartbeat from celery@qindexer.d285b752c875
[2017-08-01 20:27:02,210: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:27:03,989: INFO/MainProcess] Received task: perform_retrieval[fa7bf389-a891-4c66-b7f5-a9630eb4f1e2]  
[2017-08-01 20:27:04,079: INFO/MainProcess] Starting 1 in inception with shape (21, 1, 2048)
[2017-08-01 20:27:04,079: INFO/MainProcess] (27, 2048)
[2017-08-01 20:27:04,080: INFO/MainProcess] finished 1 in inception, current shape (27, 2048), range
[2017-08-01 20:27:04,120: INFO/MainProcess] Starting 2 in inception with shape (82, 1, 2048)
[2017-08-01 20:27:04,123: INFO/MainProcess] (109, 2048)
[2017-08-01 20:27:04,123: INFO/MainProcess] finished 2 in inception, current shape (109, 2048), range
[2017-08-01 20:27:04,154: INFO/MainProcess] Starting 2 in inception with shape (90, 1, 2048)
[2017-08-01 20:27:04,159: INFO/MainProcess] (199, 2048)
[2017-08-01 20:27:04,159: INFO/MainProcess] finished 2 in inception, current shape (199, 2048), range
[2017-08-01 20:27:04,177: INFO/MainProcess] Starting 2 in inception with shape (77, 1, 2048)
[2017-08-01 20:27:04,178: INFO/MainProcess] (276, 2048)
[2017-08-01 20:27:04,179: INFO/MainProcess] finished 2 in inception, current shape (276, 2048), range
[2017-08-01 20:27:04,180: INFO/MainProcess] Starting 2 in inception with shape (164, 1, 2048)
[2017-08-01 20:27:04,183: INFO/MainProcess] (440, 2048)
[2017-08-01 20:27:04,184: INFO/MainProcess] finished 2 in inception, current shape (440, 2048), range
[2017-08-01 20:27:04,187: INFO/MainProcess] Starting 2 in inception with shape (251, 1, 2048)
[2017-08-01 20:27:04,191: INFO/MainProcess] (691, 2048)
[2017-08-01 20:27:04,191: INFO/MainProcess] finished 2 in inception, current shape (691, 2048), range
[2017-08-01 20:27:04,196: INFO/MainProcess] Starting 3 in inception with shape (30, 1, 2048)
[2017-08-01 20:27:04,200: INFO/MainProcess] (721, 2048)
[2017-08-01 20:27:04,201: INFO/MainProcess] finished 3 in inception, current shape (721, 2048), range
[2017-08-01 20:27:04,202: INFO/MainProcess] Starting 3 in inception with shape (30, 1, 2048)
[2017-08-01 20:27:04,206: INFO/MainProcess] (751, 2048)
[2017-08-01 20:27:04,207: INFO/MainProcess] finished 3 in inception, current shape (751, 2048), range
[2017-08-01 20:27:04,429: INFO/MainProcess] Task perform_retrieval[fa7bf389-a891-4c66-b7f5-a9630eb4f1e2] succeeded in 0.439885102998s: 0
[2017-08-01 20:27:04,434: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:27:05,540: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:27:06,726: INFO/MainProcess] sync with celery@qindexer.d285b752c875
[2017-08-01 20:27:06,822: INFO/MainProcess] missed heartbeat from celery@qfaceretriever.d285b752c875
[2017-08-01 20:27:16,823: INFO/MainProcess] missed heartbeat from celery@qindexer.d285b752c875
[2017-08-01 20:28:21,849: INFO/MainProcess] missed heartbeat from celery@qindexer.d285b752c875
[2017-08-01 20:28:31,862: INFO/MainProcess] missed heartbeat from celery@qindexer.d285b752c875
[2017-08-01 20:30:14,671: INFO/MainProcess] Received task: perform_retrieval[46e9b3c7-374f-4479-a6a1-9fbcd5c6def8]  
[2017-08-01 20:30:14,706: WARNING/MainProcess] No clusterer found switching to exact search for inception
[2017-08-01 20:30:14,710: INFO/MainProcess] Starting 3 in inception with shape (1, 1, 2048)
[2017-08-01 20:30:14,716: INFO/MainProcess] (752, 2048)
[2017-08-01 20:30:14,716: INFO/MainProcess] finished 3 in inception, current shape (752, 2048), range
[2017-08-01 20:30:14,718: INFO/MainProcess] Starting 2 in inception with shape (119, 1, 2048)
[2017-08-01 20:30:14,721: INFO/MainProcess] (871, 2048)
[2017-08-01 20:30:14,722: INFO/MainProcess] finished 2 in inception, current shape (871, 2048), range
[2017-08-01 20:30:14,723: INFO/MainProcess] Starting 3 in inception with shape (19, 1, 2048)
[2017-08-01 20:30:14,724: INFO/MainProcess] (890, 2048)
[2017-08-01 20:30:14,724: INFO/MainProcess] finished 3 in inception, current shape (890, 2048), range
[2017-08-01 20:30:14,725: INFO/MainProcess] Starting 3 in inception with shape (25, 1, 2048)
[2017-08-01 20:30:14,726: INFO/MainProcess] (915, 2048)
[2017-08-01 20:30:14,726: INFO/MainProcess] finished 3 in inception, current shape (915, 2048), range
[2017-08-01 20:30:14,867: INFO/MainProcess] Task perform_retrieval[46e9b3c7-374f-4479-a6a1-9fbcd5c6def8] succeeded in 0.195651594s: 0

**Comment by AKSHAYUBHAT** [comment]
Don't see any errors there, may be the  server was waiting for the query and just got timed out. 
You can see if there are any results at <address>/queries/

It's possible that the machine did not have enough memory to load facenet model since qfaceretriever.log shows nothing after loading facenet.

**Comment by paulxiong** [comment]
you are right... it is running and waiting, no error, and eventually got the result. 
Thanks.

**Comment by AKSHAYUBHAT** [comment]
Earlier DVA used to run a separate indexer worker for processing queries only. However this doubles the memory requirement per indexing algorithm. As a result currently queries are sent to the same queue and are processed with higher priority.
