### ISSUE TITLE
detectors not working

### ISSUE THREAD

**Issue by desireB** [AKSHAYUBHAT/DeepVideoAnalytics#75]
Hi,
Thank you for this great framework.

It seems that all the detector jobs failed .
I have a Ubuntu 16.10 with GTX 1060 6GB of GPU RAM and 32 GB of RAM.

Here's the log for one : 
`
[2017-09-09 01:42:47,081: INFO/MainProcess] Connected to amqp://dvauser:**@rabbit:5672//
[2017-09-09 01:42:47,116: INFO/MainProcess] mingle: searching for neighbors
[2017-09-09 01:42:48,163: INFO/MainProcess] mingle: sync with 3 nodes
[2017-09-09 01:42:48,163: INFO/MainProcess] mingle: sync complete
[2017-09-09 01:42:48,220: WARNING/MainProcess] /usr/local/lib/python2.7/dist-packages/celery/fixups/django.py:202: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2017-09-09 01:42:48,220: INFO/MainProcess] celery@q_detector_1.d89181a20ae6 ready.
[2017-09-09 01:42:48,745: INFO/MainProcess] Received task: perform_detection[ea9c428a-ad1b-4230-86af-e60bf8df1ff8]  
[2017-09-09 01:42:48,841: INFO/MainProcess] loading detection model
[2017-09-09 01:42:52,286: INFO/MainProcess] Running coco Using filters {'video_id': 2, u'frame_index__gte': 0}
[2017-09-09 01:43:31,653: ERROR/MainProcess] Task perform_detection[ea9c428a-ad1b-4230-86af-e60bf8df1ff8] raised unexpected: InternalError()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/root/DVA/dvaapp/tasks.py", line 246, in perform_detection
    detections = detector.detect(local_path)
  File "/root/DVA/dvalib/detector.py", line 120, in detect
    [self.fname,self.boxes, self.scores, self.classes, self.num_detections])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
InternalError
[2017-09-09 01:43:31,655: WARNING/MainProcess] Substantial drift from celery@q_retriever_2.d89181a20ae6 may mean clocks are out of sync.  Current drift is
42 seconds.  [orig: 2017-09-09 01:43:31.654903 recv: 2017-09-09 01:42:49.095216]

[2017-09-09 01:43:31,655: INFO/MainProcess] missed heartbeat from celery@manager.d89181a20ae6
[2017-09-09 01:43:31,656: INFO/MainProcess] missed heartbeat from celery@q_detector_2.af8f5c6e31e6
[2017-09-09 01:43:31,656: INFO/MainProcess] missed heartbeat from celery@q_indexer_1.d89181a20ae6
[2017-09-09 01:43:31,656: INFO/MainProcess] missed heartbeat from celery@q_indexer_2.d89181a20ae6
[2017-09-09 01:43:31,656: INFO/MainProcess] missed heartbeat from celery@q_detector_3.d89181a20ae6
[2017-09-09 01:43:31,657: INFO/MainProcess] missed heartbeat from celery@qextract.d89181a20ae6
[2017-09-09 01:43:31,658: WARNING/MainProcess] Substantial drift from celery@q_retriever_1.d89181a20ae6 may mean clocks are out of sync.  Current drift is
42 seconds.  [orig: 2017-09-09 01:43:31.658031 recv: 2017-09-09 01:42:49.106468]

[2017-09-09 01:43:31,658: WARNING/MainProcess] Substantial drift from celery@q_analyzer_1.d89181a20ae6 may mean clocks are out of sync.  Current drift is
42 seconds.  [orig: 2017-09-09 01:43:31.658666 recv: 2017-09-09 01:42:49.315677]

[2017-09-09 01:43:31,659: WARNING/MainProcess] Substantial drift from celery@manager.af8f5c6e31e6 may mean clocks are out of sync.  Current drift is
41 seconds.  [orig: 2017-09-09 01:43:31.659271 recv: 2017-09-09 01:42:50.083425]

[2017-09-09 01:43:31,659: WARNING/MainProcess] Substantial drift from celery@qtrainer.d89181a20ae6 may mean clocks are out of sync.  Current drift is
41 seconds.  [orig: 2017-09-09 01:43:31.659896 recv: 2017-09-09 01:42:50.161930]

[2017-09-09 01:43:31,660: WARNING/MainProcess] Substantial drift from celery@qclusterer.d89181a20ae6 may mean clocks are out of sync.  Current drift is
41 seconds.  [orig: 2017-09-09 01:43:31.660477 recv: 2017-09-09 01:42:50.209197]

[2017-09-09 01:43:31,661: WARNING/MainProcess] Substantial drift from celery@manager.d89181a20ae6 may mean clocks are out of sync.  Current drift is
41 seconds.  [orig: 2017-09-09 01:43:31.661054 recv: 2017-09-09 01:42:50.234692]

[2017-09-09 01:43:31,661: WARNING/MainProcess] Substantial drift from celery@q_detector_2.af8f5c6e31e6 may mean clocks are out of sync.  Current drift is
41 seconds.  [orig: 2017-09-09 01:43:31.661590 recv: 2017-09-09 01:42:50.239807]

[2017-09-09 01:43:31,662: WARNING/MainProcess] Substantial drift from celery@q_indexer_2.d89181a20ae6 may mean clocks are out of sync.  Current drift is
41 seconds.  [orig: 2017-09-09 01:43:31.662126 recv: 2017-09-09 01:42:50.246742]

[2017-09-09 01:43:31,662: WARNING/MainProcess] Substantial drift from celery@qextract.d89181a20ae6 may mean clocks are out of sync.  Current drift is
41 seconds.  [orig: 2017-09-09 01:43:31.662650 recv: 2017-09-09 01:42:50.362311]

[2017-09-09 01:43:31,720: INFO/MainProcess] Received task: perform_detection[ec89923d-7b84-41dd-b788-fb25a3796ec5]  
[2017-09-09 01:43:31,807: INFO/MainProcess] Running coco Using filters {'video_id': 1, u'frame_index__gte': 0}
`

**Comment by AKSHAYUBHAT** [comment]
Hi, since you have only 6 Gb of VRAM it can be difficult to allocate enough memory for ech model (facenet, inception, face detector, mobilenet_coco_ssd) . You can try to manually tune fraction of memory allocated by changing memory_fraction in dvalib/detector.py from 0.2 to 0.45 and launch the indexer workers in CPU container so they don't use GPU. You can also edit init_models.json or remove indexer/retrievers that you don't need e.g. say facenet etc. 

Keeping multiple models in memory while still maintaining memory allocation requires tuning. Hopefully in future DVA will be able to recover automatically from such situations by dynamically keeping track of memory and failes tasks.

**Comment by desireB** [comment]
Thank you ! So it's possible to have multiple instances of DVA (i mean the components in dva-server). Workers in GPU container, and some others in CPU container ? Is there a way to define a indexer worker CPU ?
Also, I changed the memory_fraction from 0.2 to 0.45. Then I stopped all containers and started DVA. After that, I retried the indexer job, and got this error : 
`
[2017-09-09 13:22:57,023: INFO/MainProcess] Received task: perform_indexing[3c79c34c-046a-4a87-bd0d-e22ff6fc2bfc]  
[2017-09-09 13:22:57,129: INFO/MainProcess] Using batching
[2017-09-09 13:23:10,779: INFO/MainProcess] 100 batches containing 800 images indexed
[2017-09-09 13:23:28,747: INFO/MainProcess] 200 batches containing 1600 images indexed
[2017-09-09 13:23:30,693: ERROR/MainProcess] Task perform_indexing[3c79c34c-046a-4a87-bd0d-e22ff6fc2bfc] raised unexpected: IOError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/root/DVA/dvaapp/tasks.py", line 74, in perform_indexing
    perform_indexing.index_queryset(di,visual_index,start,target,queryset)
  File "/root/DVA/dvaapp/operations/indexing.py", line 76, in index_queryset
    with open(feat_fname, 'w') as feats:
IOError: [Errno 2] No such file or directory: '/root/DVA/dva/media/None/indexes/127205d6_9562_11e7_b199_0242ac130005.npy'
[2017-09-09 13:23:30,696: WARNING/MainProcess] Substantial drift from celery@q_detector_3.9d29801d39df may mean clocks are out of sync.  Current drift is
33 seconds.  [orig: 2017-09-09 13:23:30.696368 recv: 2017-09-09 13:22:57.277243]

[2017-09-09 13:23:30,698: INFO/MainProcess] missed heartbeat from celery@qclusterer.9d29801d39df
[2017-09-09 13:23:30,699: INFO/MainProcess] missed heartbeat from celery@q_analyzer_1.9d29801d39df
[2017-09-09 13:23:30,699: INFO/MainProcess] missed heartbeat from celery@q_detector_1.9d29801d39df
[2017-09-09 13:23:30,699: INFO/MainProcess] missed heartbeat from celery@q_retriever_1.9d29801d39df
[2017-09-09 13:23:30,699: INFO/MainProcess] missed heartbeat from celery@manager.9d29801d39df
[2017-09-09 13:23:30,699: INFO/MainProcess] missed heartbeat from celery@q_indexer_2.9d29801d39df
[2017-09-09 13:23:30,699: INFO/MainProcess] missed heartbeat from celery@qtrainer.9d29801d39df
[2017-09-09 13:23:30,700: INFO/MainProcess] missed heartbeat from celery@q_retriever_2.9d29801d39df
[2017-09-09 13:23:30,700: INFO/MainProcess] missed heartbeat from celery@qextract.9d29801d39df
[2017-09-09 13:23:30,700: INFO/MainProcess] missed heartbeat from celery@q_detector_2.ee6acc113adc
[2017-09-09 13:23:30,700: INFO/MainProcess] missed heartbeat from celery@manager.ee6acc113adc
[2017-09-09 13:23:30,701: WARNING/MainProcess] Substantial drift from celery@q_indexer_2.9d29801d39df may mean clocks are out of sync.  Current drift is
33 seconds.  [orig: 2017-09-09 13:23:30.700974 recv: 2017-09-09 13:22:57.283887]

[2017-09-09 13:23:30,701: WARNING/MainProcess] Substantial drift from celery@qtrainer.9d29801d39df may mean clocks are out of sync.  Current drift is
33 seconds.  [orig: 2017-09-09 13:23:30.701430 recv: 2017-09-09 13:22:57.433580]

[2017-09-09 13:23:30,701: WARNING/MainProcess] Substantial drift from celery@q_retriever_2.9d29801d39df may mean clocks are out of sync.  Current drift is
33 seconds.  [orig: 2017-09-09 13:23:30.701823 recv: 2017-09-09 13:22:57.607933]

[2017-09-09 13:23:30,702: WARNING/MainProcess] Substantial drift from celery@qextract.9d29801d39df may mean clocks are out of sync.  Current drift is
33 seconds.  [orig: 2017-09-09 13:23:30.702228 recv: 2017-09-09 13:22:57.714358]

[2017-09-09 13:23:30,702: WARNING/MainProcess] Substantial drift from celery@q_detector_2.ee6acc113adc may mean clocks are out of sync.  Current drift is
33 seconds.  [orig: 2017-09-09 13:23:30.702618 recv: 2017-09-09 13:22:57.720498]

[2017-09-09 13:23:30,703: WARNING/MainProcess] Substantial drift from celery@manager.ee6acc113adc may mean clocks are out of sync.  Current drift is
33 seconds.  [orig: 2017-09-09 13:23:30.703075 recv: 2017-09-09 13:22:57.727269]

[2017-09-09 13:23:30,703: WARNING/MainProcess] Substantial drift from celery@q_detector_1.9d29801d39df may mean clocks are out of sync.  Current drift is
32 seconds.  [orig: 2017-09-09 13:23:30.703760 recv: 2017-09-09 13:22:58.202226]

[2017-09-09 13:23:30,704: WARNING/MainProcess] Substantial drift from celery@q_retriever_1.9d29801d39df may mean clocks are out of sync.  Current drift is
32 seconds.  [orig: 2017-09-09 13:23:30.704089 recv: 2017-09-09 13:22:58.297187]

[2017-09-09 13:23:30,704: WARNING/MainProcess] Substantial drift from celery@manager.9d29801d39df may mean clocks are out of sync.  Current drift is
32 seconds.  [orig: 2017-09-09 13:23:30.704352 recv: 2017-09-09 13:22:58.372578]

[2017-09-09 13:23:30,704: WARNING/MainProcess] Substantial drift from celery@q_analyzer_1.9d29801d39df may mean clocks are out of sync.  Current drift is
32 seconds.  [orig: 2017-09-09 13:23:30.704620 recv: 2017-09-09 13:22:58.536988]
`
Thank you !

**Comment by AKSHAYUBHAT** [comment]
See this as an example of indexers on CPU and detectors with 45% memory allocated to each of them on GPU. 

https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/docker/custom/docker-compose-gpu-low-memory.yml

When you restart make sure to use `nvidia-docker-compose -f <compose file path> down -v` the -v ensures that the volumes are dropped and database / container shared file system is erased.

**Comment by desireB** [comment]
Thank you !
